### ISSUE TITLE
Cannot find module '@vidstack/react/player/layouts/default'

### ISSUE THREAD

**Issue by reyamir** [vidstack/vidstack#940]
### Current Behavior:

After install vidstack@next via `pnpm add @vidstack/react@next`, and using default layout, but I got this error

```
Cannot find module '@vidstack/react/player/layouts/default' or its corresponding type declarations.ts(2307)
```

**Comment by mihar-22** [comment]
Strange, somehow the types were not included in last release but they were there. I re-released in `1.1.6` with them 👍 Let me know if the issue persists so I can reopen.

**Comment by reyamir** [comment]
I still get same error after upgrade to v1.1.6

**Comment by reyamir** [comment]
only work version is 1.1.1

**Comment by mihar-22** [comment]
Is this with Next.js?

**Comment by reyamir** [comment]
I use vite + react router

**Comment by mihar-22** [comment]
I just tested it, found one small issue and fixed it. Try again in `1.1.7` please.

**Comment by reyamir** [comment]
this error happen again in v1.1.10, go back to 1.1.9 fixed this

**Comment by mihar-22** [comment]
Ah god damn, sorry I need to add a script to check for this missing. Not sure how it randomly doesn't get built. Fixed in `1.1.11`.
